/*
Prologue comment:
File Name: Blackjack logic
EECS 581 Project 3
Author: Zhang Chen 
Purpose: This file provide the logic for a casino game named blackjack.
The game logic is break up into multiple function to be modular, added feature and easy to maintain later on
Input: User(player) can enter the bet amount, click on the following button based on meeted condition:"deal", "hit", "stand", "double", and "reset"
Output: Shows if the player win, lose, or tie. Based on those three condition, player's currency may reduce, add, or stay netural

*/
//Global currency
document.addEventListener("DOMContentLoaded", () => {
  //local variable to get the golbal curreny in home_func.js
  let balanceDisplay = document.getElementById("balance");
  //show the GoonCoin amount
  balanceDisplay.textContent = GoonCoin;
  // assign buttons after DOM is ready by using getElementByID
  dealBtn = document.getElementById("dealBtn");
  hitBtn = document.getElementById("hitBtn");
  standBtn = document.getElementById("standBtn");
  resetBtn = document.getElementById("resetBtn");
  doubleBtn = document.getElementById("double");
  //Each button have a listener event that will trigger corresponding function when the button is click
  dealBtn.addEventListener("click", startGame);
  hitBtn.addEventListener("click", hit);
  standBtn.addEventListener("click", stand);
  resetBtn.addEventListener("click", resetGame);
  doubleBtn.addEventListener("click", doubleDown);

  // initial states of the game, where deal should be the only that can be click
  dealBtn.disabled = false;
  hitBtn.disabled = true;
  standBtn.disabled = true;
  doubleBtn,disabled = true;
});
//function to update the display balance
function updateBalance() {
  //get the element for balance and set the value to Gooncoin
  document.getElementById("balance").textContent = GoonCoin;
  //save the state of Gooncoin to ensure presistent across all game
  saveGoonCoin();
}
//Card suit arrays
const suit = ["H","C","D","S"];
//Card value array
const value = ["A","2","3","4","5","6","7","8","9","10","J","Q","K"];
//local variable for deck for blackjack
let deck = [];

//Function to create a deck of cards
function createDeck(){
  //called the local variable
  deck = [];
  //created the deck of card via two for loop and push the {suit,value} tuple into the deck
  for (let s of suit){
    for (let v of value){
      let card = {suit: s, value: v};
      deck.push(card);
    }
  }
}

//Function to shuffle the deck of cards
function shuffleDeck(){
  //for loop to shuffle the deck and make sure that is not out of bound
  for (let i = deck.length - 1; i > 0; i--){
    //using a local variable to store the random value j that is generated by java math function
    let j = Math.floor(Math.random() * (i + 1));
    //shuffle the deck by swapping array postion
    [deck[i], deck[j]] = [deck[j], deck[i]];
  }
}

//local variable to keep track of player's and dealer's hands
let playerHand = [];
let dealerHand = [];
let bet = 0;
let dealerHiddenCard = true; // Variable to track if dealer's card is hidden

//local variable to get button elements
let dealBtn, hitBtn, standBtn, resetBtn; // was const ... moved assignment into DOMContentLoaded

//Function to start the game
function startGame(){
  //using parseInt to get the user-input value for bet as int
  bet = parseInt(document.getElementById("bet").value);
  //check if the bet is none(meaning random character that is not a integer), less than 0, and bet is less than goonCoin
  if (isNaN(bet) || bet <= 0 || bet > GoonCoin) {
    //if either of those condition, alert user for invaild input
    alert("Invalid bet amount!");
    return;
  }
  //reduced GoonCoin for bet
  GoonCoin -= bet;
  //call updatedBalance function to reflected the changed balance on the webpage
  updateBalance();
  //call createdDeck function to created a deck of card
  createDeck();
  //call shuffleDeck function to shuffle the that is just created by CreatedDeck
  shuffleDeck();
  //created the array for player starting hand by storing the pop deck card
  playerHand = [deck.pop(), deck.pop()];
  //created the array for dealer starting hand by storing the pop deck card
  dealerHand = [deck.pop(), deck.pop()];
  // variable to set one of the dealer initial card as hidden(See updatedDisplay() function)
  dealerHiddenCard = true;
  //called updateDisplay() to load/updated the card image into the webpage
  updateDisplay();
  //set deal function as true to started the game, rest of the button(hit, stand, double, and reset) should be false
  //as those button is either in-game session function or end-game session function
  dealBtn.disabled = true;
  hitBtn.disabled = false;
  standBtn.disabled = false;
  doubleBtn.disabled = false;
  resetBtn.disabled = false;
  //Check if the player first hand is 21, if it is, auto stand the card
  if (getScore(playerHand) === 21){
    stand();
  }
}
//function to handle player hitting
function hit(){
  //pop a card from the deck and push it into the playerHand array
  playerHand.push(deck.pop());
  //update the webpage to shows the new card in player hand
  updateDisplay();
  //if the total card value is larger than 21, player autolose the game
  if (getScore(playerHand) > 21){
    //called endRound function that handle the "lose" message
    endRound("lose");
  //if player hand is equal to 21, then auto stand player hand
  }else if (getScore(playerHand) === 21){
    stand();
  }
  //set double button as disable, since double only show up when player hand size is less than 2
  //as long as player "hit", the player hand size will be > 2
  doubleBtn.disabled = true;
}
//function to handle player standing
function stand(){
  //show the dealer hidden card 
  dealerHiddenCard = false;
  //while loop that will check if dealer hand is less than 17
  // ( minic realistic casino behavior, where a dealer will not hit after 17, current game inplememtation is soft 17)
  while (getScore(dealerHand) < 17){
    //if it less than 17, dealer will continue to get card from the deck
    dealerHand.push(deck.pop());
  }
  //called updateDisplay() to shows dealer card
  updateDisplay();
  //created 2 constant variable that will calculate the score of player hand and dealer hand
  const playerScore = getScore(playerHand);
  const dealerScore = getScore(dealerHand);
  
  //if-elif-else statement that compared player and dealer hand
  //if dealer score is larger than 21 or player total card value beat dealer total card value
  if (dealerScore > 21 || playerScore > dealerScore) {
    //called endRound function that handle the "win" message
    endRound("win");
    //if player total card value is less than dealer total value
  } else if (playerScore < dealerScore) {
    //called endRound function that handle the "lose" message
    endRound("lose");
  } else {
    //called endRound function that handle the "push" message
    endRound("push");
  }
}
//Alex request function: Double, player can chose to double the bet in the beginning the game
function doubleDown(){
  //conditiona check to see if player have enough currency to double the bet
  if (GoonCoin < bet) {
    //if it does not have enough currency, alert the player and disable double button
    alert("Not enough GoonCoin to double down!");
    doubleDown.disabled = true;
    return;
  }
  //reduced the global currency again from initial bet aomunt
  GoonCoin -= bet;
  //double the bet
  bet *= 2;
  //updated the global currency amount
  updateBalance();
  //Player get 1 card
  playerHand.push(deck.pop());
  //updated the webpage
  updateDisplay();
  //if user total value is more than 21, player lose
  if (getScore(playerHand) > 21){
    endRound("lose");
    // any other value lower than 21, stand the player
  } else {
    stand();
  }
}
//function to reset the game
function resetGame(){
  //reset player hand array
  playerHand = [];
  //reset dealer hand array
  dealerHand = [];
  //remark dealer hidden hand as true
  dealerHiddenCard = true;
  //reset player card and dealer card section
  document.getElementById("player-cards").innerHTML = "";
  document.getElementById("dealer-cards").innerHTML = "";
  document.getElementById("player-score").textContent = "";
  document.getElementById("dealer-score").textContent = "";
  //clear the board
  clearMessage();
  //enable deal button
  dealBtn.disabled = false;
  //disable hit, stand, double button
  hitBtn.disabled = true;
  standBtn.disabled = true;
  doubleBtn.disabled = true;
  //enable reset button
  resetBtn.disabled = false;
}

//Function to update the display of cards
function updateDisplay(){
  //get the html element id of player card and dealer card section
  const playerCardsDiv = document.getElementById("player-cards");
  const dealerCardsDiv = document.getElementById("dealer-cards");
  //get the inner html element of player and dealer card section
  playerCardsDiv.innerHTML = "";
  dealerCardsDiv.innerHTML = "";

  //created a tuple to mapped the suit letter to the image suite name
  const suitMap = {
    'H': 'Hearts',
    'S': 'Spades',
    'D': 'Diamonds',
    'C': 'Clubs'
  };
  //A for loop that get the image of poker card based on player hand and dealer hand
  for (let card of playerHand){
    //created a constant image variable
    const img = document.createElement("img");
    //fetch the image from the file
    img.src = `../images/Cards/card${suitMap[card.suit]}${card.value}.png`;
    //added the image to a class
    img.classList.add("card");
    //append the image as a child to player card section
    playerCardsDiv.appendChild(img);
  }
  //get the image for dealer hand
  dealerHand.forEach((card, index) => {
  // created a constant variable to store dealer poker hand
  const img = document.createElement("img");
  //if dealer hidden card is true and the index is 0
  if (dealerHiddenCard && index === 0) {
    //show a image of a card back
      img.src = "../images/Cards/cardBack_blue3.png";
      //the rest will be normal poker card with value
  } else {
      img.src = `../images/Cards/card${suitMap[card.suit]}${card.value}.png`;
    }
    //added the image to class
    img.classList.add("card");
    //append the image as a child to dealer card section 
    dealerCardsDiv.appendChild(img);
  });
  //get the html element for player score, and updated the score using getScore function
  document.getElementById("player-score").textContent = "Score: " + getScore(playerHand);
  //if the initial dealer card is hidden, show the score as "?"
  if (dealerHiddenCard) {
    document.getElementById("dealer-score").textContent = "Score: ?";
    //if non of the dealer card is hidden, then post dealer score using getScore function
  } else {
    document.getElementById("dealer-score").textContent = "Score: " + getScore(dealerHand);
  }
}
//Function to calculate the score of a hand
function getScore(hand){
  //set initial score as 0
  let score = 0;
  //set ace amount as 0
  let ace = 0;
  //check the card in the hand
  for (let card of hand) {
    //if the card is J, Q, K, then added 10 to the score
    if (["J", "Q", "K"].includes(card.value)) score += 10;
    // if it "A"
    else if (card.value === "A") {
      //added ace amount
      ace++;
      //added 11 to the score
      score += 11;
      //rest of the score will be added using the card value array string and parse as int
    } else score += parseInt(card.value);
  }
  //a while lpp[ that will continue to check ace number, and ensure that if adding 11 will bust the hand, reduced ace to 1 
  while (score > 21 && ace > 0) {
    score -= 10;
    ace--;
  }
  //return the score
  return score;
}
//Function to handle end of round
function endRound(result){
  //set dealer hidden card as false, to show dealer hand
  dealerHiddenCard = false;
  //updated the html
  updateDisplay();
  //if result is "win", player get money
  if (result === "win") {
    //a quick check for blackjack, if player initial hand is 21, give the bet .5 higher than usual amount
    if (getScore(playerHand) === 21 && playerHand.length === 2){
      //added the winning amount to GoonCoin
      GoonCoin += bet * 2.5;
      //show a message for blackjack
      showMessage("Blackjack! You win!");
      //any other wining condition will be the just the normal times 2 amount
    }else{
    //added the winning amount to GoonCoin
    GoonCoin += bet * 2;
    //show a message for winning
    showMessage("You win!");
    }
    //if the result is lose, player doesnt gain anything and lose the bet amount(handle in startGame function)
  } else if (result === "lose") {
    //show a message that player lose
    showMessage("You lose!");
    //if dealer and player is tie in card value, it is consider a "push", where player get it bet amount back
  } else {
    GoonCoin += bet;
    showMessage("Push!");
  }
  //updated the balance
  updateBalance();
  //deal button disable
  dealBtn.disabled = true;
  //hit button disable
  hitBtn.disabled = true;
  //stand button disable
  standBtn.disabled = true;
  //double button disable
  doubleBtn.disabled = true;
  //reset button is enable
  resetBtn.disabled = false;
}
//Function to show messages to the player
function showMessage(msg){
  document.getElementById("message-area").textContent = msg;
}
//Function to clear messages
function clearMessage(){
  document.getElementById("message-area").textContent = "";
}
//Function to navigate back to homepage
function goBack() {
    sessionStorage.setItem("GoonCoin", GoonCoin);
    // Navigate and force reload so homepage reads the latest GoonCoin
    window.location.href = "../default.html";
}